# Generated by Django 4.2.1 on 2023-11-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0002_naviki'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmptyCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
                ('pathtofull', models.TextField(max_length=50, verbose_name='Путь к полному сертификату')),
                ('pathtosingle', models.TextField(max_length=50, verbose_name='Путь к одинарному серфитикату')),
            ],
            options={
                'verbose_name': 'Пустой сертификат',
                'verbose_name_plural': 'Пустые сертификаты',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Polzovatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='ФИО')),
                ('login', models.TextField(max_length=50, verbose_name='Логин')),
                ('password', models.TextField(max_length=50, verbose_name='Пароль')),
                ('email', models.TextField(max_length=50, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['-title'],
            },
        ),
        migrations.RenameModel(
            old_name='Proffessia',
            new_name='Professia',
        ),
        migrations.CreateModel(
            name='Vopros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Вопрос')),
                ('score', models.IntegerField(default=0, verbose_name='Балл')),
                ('navik1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Навык1', to='anketa.naviki')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='UserCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glavnavik', models.IntegerField(default=0, verbose_name='Основной навык')),
                ('vsenaviki', models.TextField(max_length=50, verbose_name='Все навыки')),
                ('date', models.DateField(auto_now_add=True)),
                ('polzovatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Пользователь1', to='anketa.polzovatel')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Сертификат', to='anketa.emptycert')),
            ],
            options={
                'verbose_name': 'Сертификат пользователя',
                'verbose_name_plural': 'Сертификаты пользователя',
                'ordering': ['-title'],
            },
        ),
        migrations.AddField(
            model_name='polzovatel',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Роль', to='anketa.role'),
        ),
        migrations.CreateModel(
            name='Otvet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Балл')),
                ('date', models.DateField(auto_now_add=True)),
                ('navik2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Навык2', to='anketa.naviki')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Пользователь', to='anketa.polzovatel')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='ModelProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Количество баллов')),
                ('navik3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Навык3', to='anketa.naviki')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Профессия', to='anketa.professia')),
            ],
            options={
                'verbose_name': 'Модельная профессия',
                'verbose_name_plural': 'Модельные профессии',
                'ordering': ['-title'],
            },
        ),
    ]
